# Generated by Django 2.0.9 on 2018-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
